# Generated by Django 2.2.1 on 2019-05-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('author_pic', models.ImageField(upload_to='')),
                ('author_fb_url', models.URLField()),
                ('author_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
