# Generated by Django 2.2.1 on 2019-05-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190527_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_title', models.CharField(max_length=200)),
                ('tour_content', models.TextField(blank=True, null=True)),
                ('tour_pic', models.ImageField(blank=True, null=True, upload_to='tour')),
            ],
        ),
    ]
