# Generated by Django 2.2.1 on 2019-05-29 06:44

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190529_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='tour_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
