# Generated by Django 2.2.1 on 2019-05-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190529_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='tour_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
