# Generated by Django 2.2.1 on 2019-05-30 07:29

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190530_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='tour_content2',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
